### Key Bindings

# change the prefix key
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# better split keys
bind | split-window -fhc "#{pane_current_path}"
bind \\ split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"
bind _ split-window -fvc "#{pane_current_path}"

# navigation w/o prefix
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R
bind -T copy-mode-vi C-h select-pane -L
bind -T copy-mode-vi C-j select-pane -D
bind -T copy-mode-vi C-k select-pane -U
bind -T copy-mode-vi C-l select-pane -R

# vi keys for history/copy/paste
setw -g mode-keys vi
unbind -T copy-mode-vi v
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'C-v' send -X rectangle-toggle
bind -T copy-mode-vi 'y' send -X copy-selection
bind -T copy-mode-vi d send-keys -X halfpage-down
bind -T copy-mode-vi u send-keys -X halfpage-up
bind -T copy-mode-vi Space send-keys -X page-down
bind -T copy-mode-vi Escape send-keys -X cancel

# easy pane resizing
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5

# toggle zoom
bind -n M-z resize-pane -Z
# same keybind for zoom as Windows Terminal
bind -n C-M-z resize-pane -Z

# toggle horizontal zoom
bind -n M-x if -F '#{@x_layout_save}' \
  { run 'tmux select-layout "#{@x_layout_save}" ; tmux set -u @x_layout_save' } \
  { set -F @x_layout_save '#{window_layout}' ; resize-pane -x 100% }

# toggle vertical zoom
bind -n M-y if -F '#{@y_layout_save}' \
  { run 'tmux select-layout "#{@y_layout_save}" ; tmux set -u @y_layout_save' } \
  { set -F @y_layout_save '#{window_layout}' ; resize-pane -y 100% }

### Options

# let other status bars take the bottom
set -g status-position top
set -g status-style fg=black,bg=green
set -g status-left '#{?client_prefix,#[reverse] PREFIX #[noreverse],}'

# mouse support
set -g mouse on

# start counting at 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# ensure Shift+Enter and Ctrl+Enter work
set -g extended-keys on
set -g extended-keys-format csi-u

### sensible settings I always want

# address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# increase tmux messages display duration from default 750ms
set -g display-time 2000

set -g default-terminal "screen-256color"

bind R {
    display-message "Reloading .tmux.conf ..."
    source-file ~/.tmux.conf
    display-message "Configuration reloaded"
}

### Plugins

# managed plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# plugin configuration
set -g @resurrect-processes 'cat bat btop'

#set -g @continuum-restore 'on'

# initialize plugin manager (keep this at the very bottom of tmux.conf)

# Ensure tpm is installed. Use tpack if nothing is already installed instead of
# https://github.com/tmux-plugins/tpm

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmuxpack/tpack ~/.tmux/plugins/tpm'"

if-shell "test -f ~/.tmux/plugins/tpm/tpm" \
    "run-shell '~/.tmux/plugins/tpm/tpm'" \
    "run-shell 'echo \"No tmux plugin manager installed!\">>~/tmux-errors.log''"
