# Ensure user bin directory on PATH
$env:PATH = "C:\Users\pabra\bin;$env:PATH"

# Exit profile early if not running interactively
if (-not ($Host -and $Host.UI -and $Host.UI.RawUI)) { return }

Import-Module gsudoModule

Set-PSReadLineOption -EditMode Vi
Set-PSReadLineOption -ViModeIndicator Cursor
Set-PSReadLineOption -PredictionSource HistoryAndPlugin
Set-PSReadLineOption -Colors @{ Command = 'Cyan'; Operator = 'Yellow' }

Set-PSReadLineKeyHandler -Key Tab -Function Complete

# UTF-8 for native command output and input
if ([Console]::OutputEncoding.CodePage -ne 65001) { chcp 65001 > $null }
[Console]::InputEncoding  = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
$OutputEncoding = [Console]::OutputEncoding

. "$HOME\Documents\PowerShell\Scripts\Set-WindowsTheme.ps1"

# vvvvvv to organize/cleanup vvvvvv

# perhaps use `where` defined in linux-parity to see if zoxide is available
Invoke-Expression (& { (zoxide init powershell | Out-String) })

# Required for shell integration with Intelligent Terminal
Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned

#f45873b3-b655-43a6-b217-97c00aa0db58
# >>> intelligent-terminal shell-integration >>>
# Auto-generated by Intelligent Terminal. Do not edit between markers.
# Documents is resolved at runtime so this survives OneDrive Known
# Folder Move and is a silent no-op on machines without IT installed.
$__it_si = Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'PowerShell\shell-integration_v1.ps1'
if (Test-Path -LiteralPath $__it_si) { . $__it_si }
Remove-Variable __it_si -ErrorAction SilentlyContinue
# <<< intelligent-terminal shell-integration <<<

